version: "3.9"

networks:
    mail:
        name: mail

services:
    mailpit:
        image: ${MAILPIT_CONTAINER:-axllent/mailpit:latest}
        container_name: ${MAILPIT_CONTAINER_NAME:-mailpit}
        restart: unless-stopped
        environment:
            MP_MAX_MESSAGES: 5000
            MP_DATA_FILE: /var/lib/mailpit/data/mailpit.db
            MP_SMTP_AUTH_ACCEPT_ANY: 1
            MP_SMTP_AUTH_ALLOW_INSECURE: 1
        ports:
            - ${FORWARD_MAILPIT_PORT:-1025}:1025
            - ${FORWARD_MAILPIT_WEB_PORT:-8025}:8025
        volumes:
            - ${MAILPIT_CONTAINER_MOUNT:-./database/mailpit}:/var/lib/mailpit/data
        networks:
            - mail